name: run main.py

on:
  schedule:
    - cron: '0 5 * * *' # At 05:00 on daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4' # install the python version needed
          cache: 'pip' # caching pip dependencies

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          DB: ${{ secrets.DB }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          API_USER: ${{ secrets.API_USER }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: python main.py

      - name: Send some mail
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: BZAN 545 Github Action Complete
          body: Job status - ${{job.status}}
          to: aholme27@vols.utk.edu, tdykes2@vols.utk.edu, asajjad@vols.utk.edu
          from: alexgronkowski6@gmail.com
